### ISSUE TITLE
make build fails

### ISSUE THREAD

**Issue by gtcbreizh** [jedie/docker-yaota8266#1]
Trying to build yaota8266 an error occurs at 
Step 7/8 : RUN set -x && id && rm /etc/passwd && rm /etc/group &&  addgroup --system -gid $DOCKER_UGID mpy && adduser --system  --shell="/bin/bash" --uid $DOCKER_UID -gid $DOCKER_UGID mpy && mkdir -p /mpy/build/ && chown mpy:mpy -Rf /mpy
---> Running in c6032d0b56dc
+id
uid=0(root) gid=0(root) groups=0(root)
+rm /etc/passwd
+rm /etc/group
+addgroup --system -gid 0 root
Adding group 'root' (GID 0) ...
Done
+adduser --system --uid 0 -gid 0 root
Adding system user 'root' (UID 0)  ...
Adding new user 'root' (UID 0) with group 'root' ...
Creating home directory '/home/root' ...
+addgroup --system -gid 0 mpy
And here is the error : addgroup: the GID '0' is already in use
Then the build stops indicating the command for step 7 fails.

Would you please help me to solve the error in the build ?

**Comment by gtcbreizh** [comment]
I succeeded to compile yaota8266.bin by changing the addgroup and adduser commands in Dockerfile. I replaced them by the addgroup and adduser ones found in docker-micropython project Dockerfile.

**Comment by jedie** [comment]
> addgroup: the GID '0' is already in use

Hm. Why '0' ? So `$DOCKER_UID` is 0 ... You have start the build via sudo as root?

So it may be helpful to add a check in https://github.com/jedie/docker-yaota8266/blob/master/Makefile to prevent use with sudo and output a helpful error message.

**Comment by gtcbreizh** [comment]
Yes I used "sudo make build" because "make build" only said "permission is denied".
Nevertheless I shall try the new Makefile.
Sorry but I am not an Linux expert ! I try to learn !!!!
