### ISSUE TITLE
Second make build fails

### ISSUE THREAD

**Issue by gtcbreizh** [jedie/docker-yaota8266#3]
A new error occurs with the command
'    && adduser --system --shell="/bin/bash" --uid $DOCKER_UID -gid $DOCKER_UGID mpy \' translated
+adduser --system --shell="/bin/bash" --uid 1000 -gid 1000 mpy 
Adding system user 'mpy' (UID 1000) ...
Adding new user 'mpy' (UID 1000) with group 'mpy' ...
The error arrives now
useradd invalid shell "bin/bash"
adduser '/usr/bin/useradd -d /home/mpy -g 'mpy' -s bin/hash -u 1000 mpy' returned error 3. Exiting.
I think the error is because the attributed $DOCKER_UID and $DOCKER_UGID values (1000 for each) are inadequate. In fact these values are already my uid and gid user.
How can I solve this ?

**Comment by jedie** [comment]
> invalid shell "bin/bash"

Strange. Because it's in the docker container. And it must be exists there.

UID 1000 is ok, it's the first normal user under e.g. ubuntu... Its the same here on my system, e.g.:
```
$ id
uid=1000(jens) gid=1000(jens) Gruppen=1000(jens),..
```
What linux do you use? What docker version?
Please paste your complete output. You can use https://gist.github.com/ for this.

**Comment by gtcbreizh** [comment]
[gtc.log](https://github.com/jedie/docker-yaota8266/files/4081399/gtc.log)

**Comment by gtcbreizh** [comment]
I use docker 19.03.5, lubuntu 18.04.3LTS in Oracle VirtualBox.
I remind you that I succeeded to compile yaota.bin by attributing to mpy uid and gid = 1010 in Dockerfile.
See attached gtc.log relating the second make build fails. Perhaps it will help you to understand 'invalid "bin/bash"  ' error ?

**Comment by jedie** [comment]
Ah!

I see: **--shell=bin/bash**
But it must be: **--shell=/bin/bash**

Think that's it.

**Comment by gtcbreizh** [comment]
@jedie  Ok it works by starting from scratch. Thanks for your help
